name: Test and Deploy Backend Development

on:
  push:
    branches:
      - development
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore ./backend
      - run: dotnet build ./backend --no-restore --configuration Release
      - run: dotnet test ./backend --no-build --verbosity normal --configuration Release

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Trigger Render deploy webhook
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL_BACKEND_DEV }}
        run: curl -X POST $RENDER_DEPLOY_HOOK_URL
